{
 "title": "Grafana metrics",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Server State",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "up{job=\"grafana\"}"
    }
   ]
  },
  {
   "title": "Grafana Memory",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"grafana\"}"
    }
   ]
  },
  {
   "title": "number of requests served by Prometheus",
   "type": "graph",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(http_request_total{method=\"get\"})"
    }
   ]
  }
 ]
}